set -sg escape-time 0
set -g history-limit 5000
set -g base-index 1
setw -g pane-base-index 1
set -g mouse off
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"#

unbind C-b
set -g prefix C-s
bind C-s send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

unbind Space
bind - split-window -h -c "#{pane_current_path}"
bind . split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind j swap-pane -D
bind k swap-pane -U

bind Down   swap-pane -D
bind Up     swap-pane -U

set -g status-position top
set -g status-bg white
set -g status-left '#[fg=#00000e,bold]#S'
set -g status-right '#[fg=#00000e,bold]│ %H:%M │ %d-%b-%y '
set -g pane-border-style 'fg=#30363d'
setw -g window-status-current-format '#[fg=#00000e,bold] #I:#W '
set -g pane-active-border-style 'fg=#00e68a'

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
